### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by h-ashraf** [conradcoding/movie-database#9]
Can you export the database and upload it on this as well please

**Comment by alexmelia41** [comment]
If you haven't already go to XAMPP Control Panel -> Click Config Button on Apache -> Select php.ini -> find post_max_size and upload_max_filesize and change it to 300M.

Then go to File Explorer -> xampp -> phpMyAdmin -> libraries -> config.default -> Open it in VS Code and find '$cfg['ExecTimeLimit'] and change it to a large number

Create a database in phpMyAdmin and call it 'rbb'. Go into the database and select import then select rbb source file.

Github doesn't support the file type so it can't be uploaded here. Just go in discord -> documents and the zip file is there.
